# Generated by Django 2.1.4 on 2020-04-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articleTitle', models.CharField(max_length=128)),
                ('articleContent', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='User_id',
            field=models.ForeignKey(on_delete='CASCADE', to='blogapp.User'),
        ),
    ]
