# Generated by Django 2.1.4 on 2020-04-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200423_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.User'),
        ),
    ]
